### ISSUE TITLE
The config file is one directory above bin/www

### ISSUE THREAD

**Issue by danielo515** [nomiddlename/log4js-example#4]
In the configuration of www seems that config directory is in the same level (because of the `./`) but it is actually one level above
https://github.com/nomiddlename/log4js-example/blob/master/bin/www#L21

Should not it be `../` ?

Regards

**Comment by nomiddlename** [comment]
It assumes you used `npm start` - which means the path to config is relative to the directory you started node in, which would be the same one as `package.json`.

**Comment by danielo515** [comment]
Ok, my fault then.
Thank you very much.
